search_paths = [ "/home/nic/projects" ]

[default]
[[default.window]]
window_name = "vim"
primary = true
cmd = "vim ."

[[default.window]]
window_name = "Runner"
cmd = """
lazydocker
"""

[[default.window]]
window_name = "OpenCode"
cmd = """
opencode .
"""


[[project]]
name = "mux-session"

[[project.window]]
window_name = "nvim"
primary = true
cmd = "vim ."

[[project.window]]
window_name = "tester"

[[project.window.panel_config]]
panel_direction = "h"
cmd = "make test"

[[project.window.panel_config]]
panel_direction = "h"
cmd = "btop"

[[project.window]]
window_name = "opencode"
cmd = "opencode"

[[project.window]]
window_name = "Fetcher"
cmd = """
git fetch
exit
"""
